snapshot-labs/snapshot-hub

server/helpers/database/schema.sql
- Using `INDEX` keyword to create the column indexes.
- Removed back-tic ` `` ` to solve SQL error in Postgres (the column names are always created in lower case).
The same schema.sql can be used for MySQL and Postgres - tested both.
=> Make the schema compatible with Postgres

src/routes/api.ts
Fixes # https://github.com/snapshot-labs/snapshot/issues/922
Strategies might be used multiple times in a space, so as plugins. 
Try to deduplicate strategies and plugins by name before processing it for each space.
response from  https://snapshot-hub-master-udn6q21tgz.herokuapp.com/api/explore
shows that we have 12 spaces using ticket strategy
After checking https://snapshot-hub-master-udn6q21tgz.herokuapp.com/api/spaces 
find there are 12 spaces using that strategy with 1 space use it twice. So the result is now correct.
=> fix spaces count for strategy and plugin

.github/workflows/docker-publish.yml, Dockerfile, docker-compose.yml
- Updated docker-compose to work with latest version of snapshot-hub 
- Added gh workflow to publish the docker image to the Github Container Registry
=> chore: updated docker compose and added gh workflow

src/graphql/operations/space.ts, src/graphql/operations/spaces.ts, src/graphql/schema.gql
Added a `JOIN` to the space queries, to count followers and added a `followerCount` to the Space type.
This affects all GraphQL queries now but I can also make it depend on `followerCount` being present or not. But we need to work on the hub quite a bit anyway so I left it that simple.
Note:
- `Object.assign` to not loose data from the query after using `formatSpace`
- `parent` => `_parent`: Just a naming convention for unused parameters (doesn't belong here, shame on me)
=> followerCount for space(s)

src/graphql/operations/space.ts, src/graphql/operations/spaces.ts
Fixes spaces without followers not loading.
reason:
`JOIN` = null, if there's nothing on the right side table
`LEFT JOIN` = keep "left" table data, even if right side is empty
=> fixed query to not return null if no followers

src/helpers/spaces.ts
Currently you have to wait 32 seconds for the explore endpoint to return something, every time you restart the hub, which is a bit annoying during development. So that function is now simply called right after loading the spaces.
=> load space metadata right after loading spaces

src/graphql/examples.ts, src/graphql/helpers.ts, src/graphql/schema.gql
Added network property which will be later used to display the network in the space settings for each strategy.
=> feat(): add network property to strategy

src/scores/index.ts
Since this confused me now multiple times and it's not decided how exactly to solve it, I added this comment and [this issue](https://github.com/snapshot-labs/snapshot-hub/issues/268).
=> added comment on function

src/graphql/schema.gql, src/helpers/database/schema.sql
Quorum is of type float in `SpaceVoting` but on proposal [it was now added](https://github.com/snapshot-labs/snapshot-hub/pull/282/files) as int.
In my local env I had 0.5 (ETH) set as a quorum, which was now suddenly rounded to 1 in the proposal table, leading to surprises when prioritizing it over the space setting.
(Not sure about the reasoning behind `64/30` for the scores field but I used the same values for quorum now. Should be more than sufficient.)
=> changed proposal quorrum to float/decimal

src/writer/vote.ts
Choices starting at 1 was not enforced in the hub, leaving the possibility of a custom integration sending 0 and also calculating and displaying results accordingly.
=> enforce min value 1 for choices in basic and single-choice

src/ingestor/personalSign/index.ts
This is the first step to deprecate personal sign, we would now reject personal sign messages which not come from a Safe. Safe always sign with a 0x signature so it's easy to detect.
=> Reject personal sign messages except for Safes

src/helpers/utils.ts, src/ingestor/writer/proposal.ts
Currently we do this check on Snapshot.js, with this PR I'm moving the logic to allow authors to publish a proposal as a core feature.
=> Move authors and onlyMembers validation to the hub

src/graphql/helpers.ts, src/graphql/schema.gql
Fixes [2844](https://github.com/snapshot-labs/snapshot/issues/2844).
**To merge with:**
- [snapshot.js](https://github.com/snapshot-labs/snapshot.js/pull/746)
- [snapshot](https://github.com/snapshot-labs/snapshot/pull/3265)
- add `aliased` parameter to the `space.voting` settings
=> Space settings: add aliased param to space voting setting

src/graphql/helpers.ts
We now default to `any` validation instead of `basic`
Merge only after https://github.com/snapshot-labs/snapshot-sequencer/pull/30
=> Default to  `any` validation

.env.example
We moved this env to snapshot-sequencer, so not used anywhere on the hub
=> Remove DEFAULT_NETWORK env variable

src/graphql/helpers.ts
There are still a few spaces that use `space.filters.minScore` but have empty  validations, which means it is a basic validation and uses space strategies
example space:
https://hub.snapshot.org/api/spaces/gnosis.eth 
Reported by:
https://discord.com/channels/707079246388133940/1090583087156572231/1090583087156572231
=> Fix default validation if minScore exist in filters

.env.example, package.json, src/graphql/index.ts, src/helpers/keycard.ts, src/helpers/rateLimit.ts, src/index.ts, yarn.lock
If you want to pass headers into the GraphQL editor, with this PR we can see a Request headers tab beside Query variables like in the below screenshot (make sure to hard reload if you don't see it)
Admin tasks:
=> Integrate with keycard

.github/workflows/lint.yml, .github/workflows/test.yml, package.json, tsconfig.json
The current "Test" task on CI is not running test, but lint
The lint task is running with --fix, so all errors will be ignored
Rename the task, and raise errors on lint task
- Rename task from Test to Lint
- the `lint` task should raise warnings on errors, so removing the `--fix` argument
- Add a new `typecheck` task, to lint Typescript 
- Run `yarn lint`
- Run `yarn typecheck`
=> chore: fix lint task

package.json, tsconfig.json, yarn.lock
The current production app is run directly with `ts-node` on typescript file, instead of with `node` on compiled js files.
This result in 10x more memory consumption.
My guess is that that solution was retained because the build workflow (`tsc`) does not copy the `gql` file to the final build directory.
- Run production app with `node` instead of `ts-node`
- Build files and run the production app with `node` command
- Add a post-build task to copy the `gql` file to the build directory
- Run `yarn build`
- Run `yarn start`
- It should start the app
=> chore: add build workflow

src/graphql/operations/proposals.ts, src/graphql/schema.gql
How to test:
- To return all proposals:
```
{
proposals(first:1000){
id
space {
id
}
flagged
}
}
```
- To return only flagged proposals:
```
{
proposals(first:1000, where:{flagged:true}){
id
space {
id
}
flagged
}
}
```
- To return only nonflagged proposals:
```
{
proposals(first:1000, where:{flagged:false}){
id
space {
id
}
flagged
}
}
```
=> Query to filter flagged proposals

.github/workflows/create-sentry-release.yml
The workflow is using `main` instead of `master`, thus not being triggered
=> chore: fix wrong branch name in workflow

src/helpers/moderation.ts, src/helpers/strategies.ts
Retrieving data frequently from our own some services (sidekick and score) can temporary fail for various reasons (deploy progress, etc ...)
From the sentry logs, we can see that these fail at least once a day. 
As the data is already cached, and the query is for updating it periodically, the query is allowed to fail a few times without real impact, and should raise an error only when it fails consecutively.
All temporary network errors should be muted, unless they're raised consecutively more than N times (which means something really wrong, and not temporary). 
This will remove a lot of noises from our error reporting.
Fixes SNAPSHOT-HUB-5
Fixes SNAPSHOT-HUB-6
Fixes SNAPSHOT-HUB-8
- Add a counter to store the number of times the query fail
- When a query fails consecutively more than n …
=> chore: allow a certain number of fails before reporting the error to Sentry

package.json, src/helpers/metrics.ts, src/index.ts, yarn.lock
- Install `@snapshot-labs/metrics`
- Expose basic metrics and custom metrics
=> feat: add basic metrics

src/graphql/helpers.ts
Fix #648 
Fix SNAPSHOT-HUB-C
Fix error when people are passing invalid (negative) values to `skip` and `first` argument, such as 
```
query Votes {
votes(first: -20, skip: -20, where: {proposal: "", created_gte: 0}, orderBy: "created", orderDirection: asc) {
id
voter
created
choice
reason
space {
id
}
}
}
```
=> fix: fix error when passing invalid first and skip value to SQL

.github/dependabot.yml
Dependabot only updates package for snapshot.js. It should also monitor all other packages from  @snapshot-labs orgs
Make dependabot create PR on new packages from the same org
- relax dependabot rule to include all packages from @snapshot-labs
- N/A
=> chore: relax dependabot rule

package.json, src/helpers/metrics.ts, yarn.lock
- Update snapshot-sentry to latest (add support for JSON-RPC error)
- Update snapshot-metrics to latest (add support for pushgateway, and embedded `express_open_connections_size` metrics)
=> chore: upgrade metrics package

src/helpers/metrics.ts
The metrics endpoint is logging a lot of noise from the `/graphql` path, due to people trying to find vulnerabilities, and getting metrics for path like `/graphql/../../[random-system-file]`
Ignore all those request by grouping all requests under just `/graph` endpoint
- Normalize all path starting by `/graphql`
- N/A
=> chore: normalize graphql path in metrics

src/graphql/helpers.ts, src/graphql/operations/proposals.ts, src/helpers/schema.sql
- Fix query builder to get flagged/not flagged proposals
- modified graphql helper
- fix SQL schema
TODO:
```sql
ALTER TABLE proposals 
ADD COLUMN flagged INT NOT NULL DEFAULT 0,
ADD INDEX flagged (flagged);
```
Notes:
This PR doesn't remove the previous implementation and is backward compatible. The previous implementation will be removed when data is migrated from the laser DB to the new column. Probably it will be done in a separate PR
=> feat(flag proposal): add ability to flag proposal

src/graphql/operations/index.ts, src/graphql/operations/roles.ts, src/graphql/schema.gql
To get roles of an address across all spaces 
- Run this following query with an address that is `admin` or `moderator` or `member` of space
```
{
roles(where:{address:"0xef8305e140ac520225daf050e2f71d5fbcc543e7"}) {
space
permissions
}
}
```
=> feature: Add new roles query

.env.example, README.md, docker-compose.yml, src/graphql/operations/messages.ts, src/helpers/mysql.ts, test/.env.test
Related to https://www.notion.so/snapshotlabs/Move-all-messages-to-sequencer-f7843f0b1f3049b79f87647ca652d181
- use sequencer DB for messages table
Add following `env` to digitalocean
=> feat: Use sequencer DB for messages

src/helpers/spaces.ts
This will reduce ranking score for spaces using these strategies
=> fix: Ignore api strategies from ranking calculation

package.json, src/graphql/index.ts, yarn.lock
We get the following notice
```bash
This package has been deprecated and now it only exports makeExecutableSchema.
And it will no longer receive updates.
We recommend you to migrate to scoped packages such as @graphql-tools/schema, @graphql-tools/utils and etc.
Check out https://www.graphql-tools.com to learn what package you should use instead!
```
so moved to this new package, and everything looks to be working fine
=> fix: Move from graphql-tools to @graphql-tools/schema

jest.config.ts, package.json, src/api.ts, test/setup.ts, test/setupDb.ts, test/teardown.ts
Add a yarn task `yarn test:setup` to help setup the test env
The task will recreate the test database, and import the schema
=> chore: add test env setup script

src/helpers/metrics.ts
Current graphql requests are not instrumented
Will answer this kind of question: https://discord.com/channels/955773041898573854/1103266859870081114/1161683893968183367
Instrument the graphql requests, to extract the number of requests and response time per type (Space, Proposals, Votes, etc...)
- Add middleware to instrument the graphql requests
- Start the service
- Send some requests to http://localhost:3000/graphql
- Go to http://localhost:3000/metrics
- You should see metrics with the key `graphql_requests_duration_seconds_bucket `
=> fix: instrument graphql requests

src/graphql/helpers.ts, src/graphql/operations/follows.ts, src/graphql/operations/proposal.ts, src/graphql/operations/proposals.ts, src/graphql/operations/ranking.ts, src/graphql/operations/subscriptions.ts, src/graphql/operations/vote.ts, src/graphql/operations/votes.ts
- Right now we use, `verified` and `flagged` properties from space data stored in memory
- With this change we use these fields from DB itself
Run following queries:
```GraphQL
{
votes(first:1000, where:{space:"thanku.eth"}) {
id
space{
id
verified
flagged
}
}
}
```
```GraphQL
{
vote(id:"0x461f550ed3422613af414e6d373d62bfda37cd8deb681b6196c7cffb5eed403e"){
id
space{
id
verified
flagged
}
}
}
```
from `votes` query query with `proposals`, `follows`, `subscribtions`
=> fix: Use space's verified and flagged fields from DB

package.json, src/api.ts, src/helpers/spaces.ts, test/e2e/space.test.ts, test/fixtures/spaces.ts, yarn.lock
The `/api/spaces/:SPACE_ID` endpoint is pulling data from the space's cache.
It's not using any additional data set by the cache (such as metrics), and data can be pulled directly from the database using a simple `SELECT` query, bypassing the cache and it's latency, and reducing side effect by using the cache.
Using the cache is making the code impossible to tests
- Use space data from the database directly
- Use data from database directly
- Add some tests
- get `/api/spaces/[ID]` => it should return same data as before
=> fix: `/api/spaces/ID` should pull data from DB instead of cache

src/helpers/alias.ts
The file does not seem to be used anywhere, a search on the `isValidAlias` keyword does not yield any results.
=> fix: remove unused alias helper

src/helpers/spaces.ts, test/setup.ts, test/setupDb.ts
This PR add additional securities to ensure test suite are only run on test database.
The convention will be to always prefix test database with `_test`. `yarn test:setup` is provided to automatically setup the test database
=> chore: ensure test suite are only run on test database

src/helpers/metrics.ts
Fix #729
Fix SNAPSHOT-HUB-1D
Fix SNAPSHOT-HUB-1B
Check that value is defined before usage
=> fix: check for value before manipulation

src/helpers/metrics.ts
Fix #727 
Fix [SNAPSHOT-HUB-19](https://snapshot-labs.sentry.io/issues/4545184002/?referrer=github_integration)
Stop logging graphql syntax errors from the metrics middleware
=> fix: skip logging graphQl Errors

package.json, src/graphql/operations/vp.ts, yarn.lock
Upgrade snapshot.js to 0.8.0-beta.0, with `ofetch` migration.
- Add try/catch around snapshot.utils function, and return a more meaningful error
- Return error when space or proposal are not found
- Return error when voter is blank (ideally, we should check that it's a valid address here)
There's only one file affected: operation/vp.ts
Should also fix #413 
Before upgrade, error response
```json
{
"errors": [
{
"message": "Unexpected error value: { code: 500, message: \"unauthorized\", data: {} }",
"locations": [
{
"line": 2,
"column": 3
}
],
"path": [
"vp"
]
}
],
"data": {
"vp": null
}
}
```
After upgrade, error response:
```json
{
"errors": [
{
"message": "request failed",
"locations": [
{
"line": 2,
"column": 3
}
],
"path": [
"vp"
]
}
],
"data": {
"vp": null
}
}
```
Working query 
``` …
```
=> fix: upgrade snapshot.js to 0.8.0 beta.0

src/graphql/operations/vp.ts
in `vp` operation, check that proposal and space exist, and return meaningful error otherwise.
With this test query 
```
query Vp{
vp(
space: "rocketposfsdfol-dao.eth",
proposal: "asas",
voter: "0x0000000000000000000000000000000000000000",
) {
vp
}
}
```
Before fix, it returns 
```
{
"errors": [
{
"message": "Cannot read properties of undefined (reading 'network')",
"locations": [
{
"line": 2,
"column": 3
}
],
"path": [
"vp"
]
}
],
"data": {
"vp": null
}
}
```
After fix, it returns
```
{
"errors": [
{
"message": "space not found",
"locations": [
{
"line": 2,
"column": 3
}
],
"path": [
"vp"
]
}
],
"data": {
"vp": null
}
}
```
=> fix: check space and proposal exist

src/graphql/operations/vp.ts
Fail early and return meaningful when voter address is invalid on `vp` query
Before, when passing `0x0000000000000000000000000000000000000000` or `` as voter, it calls score-api then returns:
```
{
"errors": [
{
"message": "Unexpected error value: { code: 400, message: \"unauthorized\", data: \"invalid address\" }",
"locations": [
{
"line": 2,
"column": 3
}
],
"path": [
"vp"
]
}
],
"data": {
"vp": null
}
}
```
Now, it should return the error without calling score-api
```
{
"errors": [
{
"message": "invalid address",
"locations": [
{
"line": 2,
"column": 3
}
],
"path": [
"vp"
]
}
],
"data": {
"vp": null
}
}
```
Test with following query
```
query Vp{
vp(
space: "rocketpool-dao.eth",
voter: "0x0000000000000000000000000000000000000000",
) {
vp
}
}
```
=> fix: return an error on invalid voter address

src/api.ts, src/helpers/metrics.ts, src/helpers/moderation.ts, src/helpers/spaces.ts, src/index.ts
Extracted from #712 
Trigger the space and moderation data refresher manually, instead of automatically on import.
This allow skipping the refresh, and is particularly useful on test suite
=> refactor: trigger data refresher manually

src/graphql/helpers.ts, src/helpers/schema.sql, test/fixtures/spaces.ts
Ref to #726 
Rename the `created_at` and `updated_at` properties in Space to just `created` and `updated`, to be consistent with the all the other objects.
Run the following query 
```sql
ALTER TABLE spaces RENAME COLUMN created_at TO created;
ALTER TABLE spaces RENAME INDEX created_at TO created;
ALTER TABLE spaces RENAME COLUMN updated_at TO updated;
ALTER TABLE spaces RENAME INDEX updated_at TO updated;
```
=> fix: rename `_at` suffix from Space timestamp properties

src/graphql/helpers.ts, src/graphql/schema.gql
Fix #714 
We're limiting the space to 30k, which is a hard limit, since the Space query does not provided any filters to paginate.
This PR adds a `created` filter in where, to enable paginating the Space object, like the Vote object.
This enable query like 
```graphql
query Spaces {
spaces(first: 10, skip: 5, where: {created_gt: 1697661410}) {
name
created
}
}
```
=> fix: fix space query unable to get past 30k spaces

README.md
the text is confusing, someone using hub doesn't have to provide URL to us, it should run individually
=> fix: Remove confusing documentation

src/helpers/spaces.ts
Fixes https://github.com/snapshot-labs/pitches/issues/47
How to test:
- Create a test proposal on your space, `activeProposals` on `Space` query should return `1`
- Mark proposal as flagged
- Count should be `0`
=> Fix: Exclude flagged proposals from active proposals count

src/graphql/helpers.ts
Fixes #757 
GraphQL filters with empty array now return an error, like on https://api.lens.dev/graphql
Test with 
```graphql
query Spaces {
spaces(first: 5, skip: 0, where: {id_in: []}) {
name
created
}
}
```
Should return 
```json
{
"errors": [
{
"message": "id_in must have at least one item",
"locations": [
{
"line": 2,
"column": 3
}
],
"path": [
"spaces"
]
}
],
"data": {
"spaces": null
}
}
```
Additionally, move all `throw new Error` to `throw new PulbicError` for consistency
=> fix: empty array in graphql filters should trigger an error

src/graphql/helpers.ts
Reverts snapshot-labs/snapshot-hub#763
Looks like UI still send empty array sometimes, we need to fix those first 
For example in proposals page
https://discord.com/channels/707079246388133940/1090304570015629365/1179358781788913674
=> Revert "fix: empty array in graphql filters should trigger an error"

src/graphql/helpers.ts
Fixes #757 
Return an empty response when array filter is empty
Retry of https://github.com/snapshot-labs/snapshot-hub/pull/763 which was reverted
Test with 
```graphql
query Spaces {
spaces(first: 5, skip: 0, where: {id_in: []}) {
name
created
}
}
```
Should return 
```json
{
"errors": [
{
"message": "id_in must have at least one item",
"locations": [
{
"line": 2,
"column": 3
}
],
"path": [
"spaces"
]
}
],
"data": {
"spaces": null
}
}
```
Additionally, move all `throw new Error` to `throw new PulbicError` for consistency
=> fix: return empty results on empty array filters

src/api.ts
Use status code `410` for removed API endpoint.
Goal is to reduced the number of returned 500 errors, as it's skewing metrics
=> chore: use more relevant status code

src/graphql/schema.gql, src/helpers/schema.sql
The field is already added in the testnet and livenet db. This will be used to grant additional permission or advantages for spaces.
=> chore: add turbo param for spaces

src/graphql/helpers.ts
demo.snapshot.org has been renamed to testnet.snapshot.org
=> fix: update test site subdomain to `testnet`

src/helpers/spaces.ts, test/e2e/space.test.ts, test/fixtures/spaces.ts
`loadSpaces` is missing turbo field so it is unable to calculate ranking of turbo spaces
=> fix: SQL query to get space is missing turbo field

src/graphql/helpers.ts
Default value for `args` is missing for `fetchSpaces`, when called internally, and not via graphql.
Add back default args values for `first` and `skip` for `fetchSpaces`
When applied with #785, the following query should now works:
```
query Space {
space(id: "aave.eth") {
id 
}
}
```
=> fix: fix missing default when args is not coming from gql schema

src/graphql/operations/roles.ts
The role graphql query is not escaping special characters properly, making the SQL query fail in some cases.
See invalid input in [SNAPSHOT-HUB-1Q](https://snapshot-labs.sentry.io/issues/4804737954/?referrer=github_integration)
Close #787 
Close [SNAPSHOT-HUB-1Q](https://snapshot-labs.sentry.io/issues/4804737954/?referrer=github_integration)
Escape the `address` input properly by using the SQL native `JSON_QUOTE` function, instead of basic string interpolation (`"${address}"`)
- Use `JSON_QUOTE` to escape input
This query should work:
```
query { roles (where: {address: "0xd83261a97fc12d11853bfadae196b832f8aadf79"}) { permissions } }
```
Passing any incomplete address, such as `0x` should not return any result.
=> fix: fix escape issue when address contains special characters

package.json
Same setup as sequencer: always run `yarn test:setup` when running `yarn test`
=> chore: always run test setup before running test

src/helpers/metrics.ts
Normalizing `graphql` path in metrics, so that `graphql/test/abc`, `graphql?test` etc... are considered as just `graphql`
=> chore: normalize metrics path

package.json
This PR removes the `engines` property in package.json, to allow more node version.
This change will not affect the node version used on the prod server, which should remain on 16
This service have been tested, and should work on node 18
=> chore: allow node version > 16

src/helpers/metrics.ts
Fix https://snapshot-labs.sentry.io/issues/4868101610/?query=is%3Aunresolved&referrer=issue-stream&statsPeriod=30d&stream_index=0
Query is missing the `as count` name
=> fix: fix invalid query results

src/api.ts, src/helpers/spaces.ts, test/e2e/space.test.ts, test/fixtures/spaces.ts
Fixes #796 and needed by https://github.com/snapshot-labs/snapshot/issues/4516
The GET /spaces/ID endpoint can now returns deleted spaces
Test with
```bash
curl http://localhost:3000/api/spaces/TEST-ID
```
Should return the space settings (if found), with a `deleted` property
=> feat: add endpoint to check for deleted spaces

package.json, src/helpers/rateLimit.ts, yarn.lock
On redis connection issues, rate-limit middleware is blocking the whole request workflow, and not letting through any requests.
Fix #802 
On redis connection issues, rate-limit middleware should be ignored, and all requests should bypass the middleware.
- Bypass rate-limit middleware when redis is not ready
- Update `rate-limit-redis` package to 3.1.0, to support redis reconnection, else will throw https://github.com/express-rate-limit/rate-limit-redis/issues/144
- Start your redis server
- yarn dev
- Send some requests to localhost:3000
- It should returns headers like `Ratelimit-Limit`
- Stop the redis server
- It should start logging connections error on the `yarn dev` console
- Send some requests to localhost:3000
- It should return results as usual
- The headers `Ratelimit-Limit` …
=> fix: ignore redis connections error on rate limit

package.json
The `test` command may be stuck while using `start-server-and-test`, due to it listening on `127.0.0.1` instead of `localhost`. On some env, those 2 urls are the same, but not always (see https://www.npmjs.com/package/start-server-and-test#localhost-vs-0000-vs-127001)
`yarn dev` is starting on `localhost`, so `start-server-and-test` should also be explicitly told to listen on `localhost`
- Update `test` command to listen on the full url instead of just the port
- Run `yarn test`
- It should run the test
=> chore: fix `test` command stuck waiting on wrong url

src/graphql/operations/vote.ts
fixes https://github.com/snapshot-labs/snapshot-hub/issues/444
To change collation but that is not happening so calling the `votes` query will fix this for now
- Make sure your `votes` table and `spaces` tables have different collations
- try the following query
```Graphql
query Vote {
vote (
id: "0xf6c08b692d4bd1fd4c091431895309d38f3d6d7770c075c14b63fca27662b073"
) {
id
space {
id
}
}
}
```
- Before fix it should return error `Unexpected error value: \"request failed\"` 
- After fix it should return vote response
=> fix: vote query not working

src/graphql/operations/networks.ts
Right now we are counting main space network, this change will add
- Strategy network count
- Networks used inside multichain strategy
Before change:
After change:
=> fix: Include strategy networks and multichain networks in network count

src/graphql/helpers.ts, src/graphql/schema.gql
Fixes #822 
Add boost fields to space/spaces query so UI can retrieve them
- Try a query like 
```graphQL
{
space(id:"thanku.eth") {
id
boost {
enabled
bribeEnabled
}
}
}
```
- It should return default values
- Now try changing the settings of your space directly on DB (or use UI https://github.com/snapshot-labs/snapshot/pull/4616 to update your DB settings) 
-  On you DB, try adding:
```JSON
"boost":{"enabled":true,"bribeEnabled":true}
```
- Now try the above query again, it should return updated values
=> feat: Add boost fields to space query

src/graphql/helpers.ts, src/graphql/schema.gql, src/helpers/schema.sql
Related https://github.com/snapshot-labs/snapshot/issues/4600
Returns `quorumType` on proposal and space
- Change `quorumType` in your space settings
- Create proposals with different `quorumType`
Try running a query like:
```
{
spaces {
id
voting{
quorumType
quorum
}
}
}
{
proposals {
id
quorum
quorumType
}
}
```
- Should return `default` by default and `optimistic` if changed
```SQL
ALTER TABLE proposals
ADD COLUMN quorum_type VARCHAR(24) DEFAULT '' AFTER quorum;
```
=> Add Quorum type on proposal and space

src/helpers/spaces.ts
Reducing wait time to 2 mins from 6 mins, as 6 mins is quite high and it feels like something is down
=> fix: Reduce wait time to two mins while loading spaces

src/graphql/helpers.ts
This one is a temporary fix for https://github.com/snapshot-labs/snapshot-sequencer/pull/325/files to return a default value when `validation` is `{}`
ideally, we will save 
```js
{
name: 'any',
params: {}
}
```
or `null` to this field
=> Fix: vote validation default value

src/graphql/operations/ranking.ts
Fixes #841 .
Fix an error when variable is `null` instead of `string` type
=> fix: fix error when variable is null

src/graphql/operations/follows.ts, src/graphql/schema.gql, src/helpers/schema.sql
Fixes https://github.com/snapshot-labs/snapshot-sequencer/issues/341
This PR add support for the new `network` field added to follows in https://github.com/snapshot-labs/snapshot-sequencer/pull/342
- Add `network` and `network_in` filter to follows
- Return the `network` field in follows
As we only have Space data for followed spaced of type `s`, all the spaces from other network will only return an `id`, with all other fields blank.
```graphql
{
follows(where: {network: "s"}, first: 10) {
id
space {
id 
name
about
turbo
flagged
verified
}
network
}
}
```
=> feat: add support for `network` field in follows

src/graphql/helpers.ts
Return an empty `spaces` result when the `controller` filter is empty
```graphql
query Spaces {
spaces(
first: 20,
skip: 0,
orderBy: "created",
orderDirection: desc,
where: { controller: "" }
) {
id
}
}
```
Should return 
```json
{
"data": {
"spaces": []
}
}
```
and not all spaces.
=> fix: return no spaces when controller is empty

src/graphql/operations/ranking.ts
Fix invalid returned keyname, should be `items` instead of `spaces`
=> fix: fix invalid returned keyname

package.json, src/graphql/helpers.ts, src/graphql/operations/votes.ts
- Allow lowercase `voter` address on `votes` query
- Also allow inside `_not`, `_in`, `_not_in` cases 
- Try passing lowercase address in `voter` and `voter_in` 
```graphql
query Votes {
votes(
where: {voter: "0x24f15402c6bb870554489b2fd2049a85d75b982f"}
) {
id
voter
}
}
```
- `voter_in: ["0x24f15402c6bb870554489b2fd2049a85d75b982f"]`
- `voter: "0x24F15402C6Bb870554489b2fd2049A85d75B982f"`
- `voter_in: ["0x24F15402C6Bb870554489b2fd2049A85d75B982f"]`
- Should return an error if someone passes invalid address `voter: "1234"`
=> fix: Allow lowercase voter address on votes query

src/graphql/schema.gql, src/helpers/schema.sql
Related to https://github.com/snapshot-labs/sx-monorepo/pull/407
Return new statement properties
=> feat: add support for new statement properties

src/graphql/schema.gql
These inputs were never handled in rankings query
=> fix: Remove un-used id and id_in from RankingWhere

src/graphql/helpers.ts, src/graphql/operations/user.ts
Related to https://github.com/snapshot-labs/snapshot.js/pull/1032/
We don't have to return error if address is not a EVM address
=> fix: Ignore if address is not a EVM address

src/graphql/operations/leaderboards.ts
Will fix the offchain part for https://github.com/snapshot-labs/sx-monorepo/issues/480
Paginating through the leaderboard is returning duplicates items.
Adding more ordering fields
- Always sort by 3 fields (`proposal_count`, `vote_count` and `user`), to avoid duplicates when multiple rows have the same counter
- The `orderBy` field will only move the given order field to the beginning
```graphql
query {
leaderboards(
first: 20
skip: 0
orderBy: "proposal_count"
orderDirection: desc
where: {
space: "safe.eth"
}
) {
user
space
proposalsCount
votesCount
}
}
```
Increment the `skip` by 20 will not returning duplicates items from previous page
=> fix: fix duplicates items on leaderboard pagination

package.json, src/graphql/helpers.ts, src/graphql/operations/aliases.ts, src/graphql/operations/follows.ts, src/graphql/operations/leaderboards.ts, src/graphql/operations/proposals.ts, src/graphql/operations/statements.ts, src/graphql/operations/subscriptions.ts, src/graphql/operations/user.ts, src/graphql/operations/users.ts, src/graphql/operations/votes.ts, src/helpers/schema.sql, yarn.lock
Fixes https://github.com/snapshot-labs/pitches/issues/83
This PR introduces some changes in order to accept starknet address as input (in `where` and `id` fields)
- feat: add `starknetAddress` to `where` fields accepted values
- feat: allow passing an array to `where` values, so we can format using `evmAddress`, or `['evmAddress', 'starknetAddress']`
- refactor: rename `EVMAddress` to `evmAddress` in `where` fields formatter
- refactor: remove `@ethersproject/address` as dependency, will use the formatter exported by snapshot.js
- `yarn link` this branch of the SDK https://github.com/snapshot-labs/snapshot.js/pull/1032
- `yarn dev`
- you should be able to query fields by starknet address (e.g using a non padded starknet address or checksummed address, address will always be converted to …
=> fix: add support for starknet address

src/graphql/operations/proposals.ts
Fixes #892 
- Use lowercased titles to search with `LOWER`
How to test:
- Query using
```Graphql
query Proposals {
proposals(
where: {title_contains: "ARFC-ADDENDUM"}
) {
id
title
}
}
```
- Should not work before but should work after
=> fix: Use lowercased proposal title to search

src/graphql/operations/ranking.ts, src/helpers/spaces.ts
Use the new `vote_count`, `proposal_count` and `follower_count` columns from the spaces table to retrieve total number of items per space, instead of using a `COUNT(id) as COUNT` select.
Also some refactoring to add types, and cleaning.
The whole script now run in 40 seconds (instead of > 10 minutes), with 95% of the time spend on loading all spaces.
1. Connect your snapshot UI to a hub with running branch
2. Front page should load the same spaces, in the same order
=> fix: optimize spaces helpers 

src/helpers/spaces.ts
Some spaces don't have popularity when they are created, these should not be ignored by search
- Try query before and after fix, it should return space 
```graphql
{
ranking(where: {search: "ITP DAO"}) {
items {
id
}
}
}
```
=> fix: ranking query should also return spaces with no popularity

src/graphql/helpers.ts, src/graphql/schema.gql
Closes #907
This PR add a `verified` filter to the spaces `where` argument
```
query Spaces {
spaces(where: { verified: true }) {
id 
name
}
}
```
This should return a list of only verified spaces
=> feat: add `verified` field to SpacesWhere

src/graphql/operations/statements.ts, src/graphql/schema.gql, src/helpers/schema.sql
Toward https://github.com/snapshot-labs/workflow/issues/167
Add support for the new `source` column in the statements table
- Add ability to query statements by source (string and array)
- Can return `source` in Statement
- Update schema.sql to reflect new source column
To be merged after https://github.com/snapshot-labs/snapshot-sequencer/pull/422
=> feat: add support for new source column in statements table

src/graphql/helpers.ts, src/graphql/schema.gql
Toward https://github.com/snapshot-labs/workflow/issues/177
This PR will return the new `delegationNetwork` property in the Delegation Portal setting.
When the property does not exist (for old data), it will always return `1` (ethereum).
This space does not have `delegationNetwork` set, and the hub will return `1`
```graphql
query Spaces {
spaces (where: { id: "test.wa0x6e.eth"}  ){
id
delegationPortal {
delegationApi
delegationType
delegationNetwork
delegationContract
}
}
}
```
=> feat: add network to delegation portal

src/graphql/operations/votes.ts
Temporary fix for #760 
- Test with:
```GraphQL
query Votes {
votes(first: 1000, where: { voter: "0x24F15402C6Bb870554489b2fd2049A85d75B982f" }) {
id  
proposal {
id
space {
id
}
ipfs
}
}
}
```
Should return values without `null` in proposal
- 
```GraphQL
query { 
vote(id: "0xd954ffa9c8766c7f1195f867522ac759d8f752781d811941c91e289032e7df90") {
id
proposal {
id
}
}
}
```
Should return `null`
=> fix: Exclude votes without proposals

src/graphql/schema.gql
Working towards https://github.com/snapshot-labs/workflow/issues/152
This PR adds support for returning the `cover` field in the space settings when requested
See https://github.com/snapshot-labs/snapshot.js/pull/1055 for the corresponding write PR
=> feat: add support for space cover

src/graphql/schema.gql, src/helpers/spaces.ts
Towards https://github.com/snapshot-labs/workflow/issues/134
- Adds a new property proposalCount1d on spaces query
- Note that these counts gets updated every 2 mins ([approved](https://discord.com/channels/955773041898573854/1285170554395164704/1285174119079608374))
```graphql
{
spaces(where:{id:"thanku.eth"}){
proposalsCount1d
proposalsCount7d
name
}
}
```
=> fix: Add proposalCount1d on spaces

src/graphql/schema.gql, src/helpers/spaces.ts
Towards https://github.com/snapshot-labs/workflow/issues/134
I forgot about 30d limit in https://github.com/snapshot-labs/snapshot-hub/pull/925
Summary:
Adds a new property proposalCount30d on spaces query
```graphql
{
spaces(where:{id:"arbitrumfoundation.eth"}){
proposalsCount1d
proposalsCount7d
proposalsCount30d
name
}
}
```
=> fix: Add 30d proposal count to spaces

src/graphql/helpers.ts
Fix an issue where querying multiple spaces, with a combined total of subspaces > 20, is returning 20 subspaces max
=> fix: fix issue where sub spaces querying return 20 results max

src/graphql/helpers.ts, src/graphql/schema.gql
Towards https://github.com/snapshot-labs/workflow/issues/143
- Add `labels` to `spaces` query
- Add following to your space settings
```JSON
"labels": [
{
"id": "96ac1059",
"name": "Test 2",
"color": "#52AA53",
"description": "Description 2"
},
{
"id": "810fb747",
"name": "Test",
"color": "#8C5065",
"description": "Test desc."
}
],
```
- Query with your space
```GraphQL
{
spaces(where:{id:"thanku.eth"}){
labels {
id
name
description
color
}
}
}
```
=> feat: Add labels to space queries

src/graphql/schema.gql
Closes https://github.com/snapshot-labs/workflow/issues/232
This PR returns the `snapshot` property as number (since in the table, it's an INT column, and on the front end, we're expecting a number)
=> fix: return snapshot as number

src/graphql/helpers.ts, src/graphql/schema.gql, src/helpers/schema.sql
Towards https://github.com/snapshot-labs/workflow/issues/143
- Accepts labels on proposals
- Create proposals with labels using https://github.com/snapshot-labs/snapshot-sequencer/pull/449
- Or add following into labels coloumn
```
[
"e72db302",
"96ac1059"
]
```
- Run a query like
```graphql
{
proposals{
labels
}
}
```
=> feat: labels on proposal and proposals queries

src/graphql/operations/index.ts, src/graphql/operations/options.ts, src/graphql/schema.gql, src/helpers/schema.sql
Closes https://github.com/snapshot-labs/workflow/issues/223
This PR adds a new `options` endpoint to return all data from the `options` table
Endpoint do not have any filter and pagination, and will always return all results.
Create the table with
```sql
CREATE TABLE options (
name VARCHAR(100) NOT NULL,
value VARCHAR(100) NOT NULL,
PRIMARY KEY (name)
);
```
Then you can query with 
```graphql
query {
options {
name 
value
}
}
```
which should return something like 
```
{
"data": {
"options": [
{
"name": "limit.test",
"value": "12"
}
]
}
}
```
Insert data for mainnet (from https://github.com/snapshot-labs/snapshot-sequencer/blob/2a94d8fdcb592d9b087a33508eb02db76613cccd/src/helpers/limits.ts)
```sql
INSERT INTO `options` (`name`, `value`) VALUES
('ecosystem_spaces', …
```
=> feat: add new options endpoint

src/graphql/helpers.ts, src/graphql/operations/follows.ts, src/graphql/operations/proposal.ts, src/graphql/operations/proposals.ts, src/graphql/operations/subscriptions.ts, src/graphql/operations/votes.ts, src/helpers/spaces.ts, test/e2e/space.test.ts, test/fixtures/spaces.ts
Related to https://github.com/snapshot-labs/workflow/issues/241
- Use `domain` field instead of `domain` in settings JSON
- Change `domain` field and `settings.domain`
- Hub queries should return `domain` field instead of domain in JSON
=> fix: Use domain field instead of one in JSON

src/graphql/operations/proposals.ts, src/graphql/schema.gql
Toward https://github.com/snapshot-labs/workflow/issues/254
This PR adds a new `labels_in` filter to proposals where query, to retrieve proposals by labels ID
```graphql
query { 
proposals(where: {labels_in: ["764ca440", "ac7c86a4", "84da127c", "7bf634db"]}) {
id 
}
}
```
=> feat: add filter to search proposals by labels

src/graphql/operations/votes.ts
Fixes https://github.com/snapshot-labs/snapshot-hub/issues/760
- We don't have votes with `null` proposal
- Removes check for proposal in votes query 
- Use this query
```graphql
query ($spaceId: String!, $where: VoteWhere!, $orderDirection: OrderDirection!) {
votes(where: $where, orderDirection: $orderDirection) {
created
voter
}
space(id: $spaceId) {
admins
members
moderators
}
}
```
Variables
```JSON
{
"spaceId": "arbitrumfoundation.eth",
"where": {
"space": "arbitrumfoundation.eth",
"created_gt": 0
},
"orderDirection": "DE"
}
```
- It should be super slow before fix and relatively fast after fix
=> fix: Remove proposal check in votes query 

src/graphql/operations/proposals.ts
Toward https://github.com/snapshot-labs/workflow/issues/254
This PR will change how proposal's labels are searched for.
Currently, `labels_in` operates with the `OR` operator, and when searching for `[1, 2]`, will return proposals with either `1` or `2`.
This PR will change the operator to `AND` (to be consistent with all other existing `_in` filters), so that when searching for `[1, 2]`, will return results for proposals that have both `1` and `2`
=> fix: use `AND` operator when searching for multiple labels

src/graphql/schema.gql
Towards https://github.com/snapshot-labs/workflow/issues/275
- add discussions and discourseCategory fields to Space type
- Add these fields to your space using
```sql
UPDATE spaces
SET settings = JSON_SET(settings, '$.discussionLink', 'https://discuss.ens.domains/', '$.discourseCategory', 28)
WHERE id = 'thanku.eth';
```
- Run this query to get space
```GraphQL
{
space(id:"thanku.eth") {
id
discussionLink
discourseCategory
}
}
```
=> feat: add discussions and discourseCategory fields to Space

src/eip4824.ts, src/graphql/helpers.ts, src/helpers/rateLimit.ts
Closes https://github.com/snapshot-labs/workflow/issues/320
This PR will updates all public links to the new .box domain
1. Query with `query { proposals { link } }`
2. The link should use the new .box domain, and space should be prefixed with `s:`
3. In your .env, update `NETWORK` to testnet
4. Domain should be `testnet.snapshot.box` and prefix `s-tn:`
=> fix: update all links with new .box domain

src/helpers/spaces.ts
Fixes https://github.com/snapshot-labs/workflow/issues/341
Inside `loadSpacesMetrics`, we were using previous counts if metrics doesn't contain certain properties
```ts
spacesMetadata[space].counts = {
...spacesMetadata[space].counts,
...metrics
};
```  
- If there are no active proposals then `getProposals` return an object without `activeProposals` property
- If there are no active proposals / recent proposals, then `getProposals` returns empty object
- In these cases, it will show previous counts
- This PR fixes that and uses new counts
- Create a proposal that ends in 5 mins
- Try the following query
```graphql
{
space(id: "thanku.eth") {
id
activeProposals
proposalsCount1d
proposalsCount7d
proposalsCount30d
}
}
```
- `activeProposals` should be `1`
- Once the proposal end …
=> fix: wrong counts

package.json, yarn.lock
Related to https://github.com/ardatan/graphql-tools/issues/6776
- Right now all deployments are failing because of error
```bash
23 16:56:50] │ node_modules/@graphql-tools/utils/typings/fakePromise.d.ts(2,37): error TS1139: Type parameter declaration expected.
[2024-12-23 16:56:50] │ node_modules/@graphql-tools/utils/typings/fakePromise.d.ts(2,44): error TS1005: ',' expected.
[2024-12-23 16:56:50] │ node_modules/@graphql-tools/utils/typings/fakePromise.d.ts(2,51): error TS1005: ')' expected.
[2024-12-23 16:56:50] │ node_modules/@graphql-tools/utils/typings/fakePromise.d.ts(2,53): error TS1434: Unexpected keyword or identifier.
[2024-12-23 16:56:50] │ node_modules/@graphql-tools/utils/typings/fakePromise.d.ts(2,54): error TS1128: Declaration or statement expected.
[2024-12-23 16:56:50] │ …
```
=> fix: resolve graphql-tools version to 10.0.0

package.json, yarn.lock
Fixes https://github.com/snapshot-labs/workflow/issues/354
- Update typescript as mentioned in https://github.com/ardatan/graphql-tools/issues/6776
- Revert https://github.com/snapshot-labs/snapshot-hub/pull/966
- Remove node_modules
- Run `yarn` 
- Run `yarn build` 
- Build should be successful without any errors
=> fix: update typescript to fix build

src/helpers/schema.sql
Following https://github.com/snapshot-labs/snapshot-sequencer/pull/469
This PR updates the schema.sql file to be in sync with the one on the hub
=> fix: update schema.sql to reflect production database

src/helpers/spaces.ts
Issue:
On the v1 interface it says that there are 10 spaces on the Sonic network but on the v2 interface i only see 7 spaces.
The other three spaces
`heyanondao.eth`: enabled "Hide space from homepage" in settings
`beefydao.eth` and `profit.beefy.eth`: These spaces use this network inside delegation strategy, this PR adds these spaces to response
Use following query, it should return 7 spaces before and 9 spaces after fix
```Graphql
{
ranking(where: {network: "146"}) {
metrics {
total
categories
}
items {
id
network
strategies {
name
network
params
}
}
}
}
```
=> fix: include networks from delegation strategies

src/graphql/operations/networks.ts, src/graphql/schema.gql, src/helpers/schema.sql
Toward https://github.com/snapshot-labs/workflow/issues/389
See https://github.com/snapshot-labs/sx-monorepo/pull/1120#discussion_r1930677289
This PR returns the `premium` property for each network.
For this, a new table will be needed to hold network metadata:
```sql
CREATE TABLE networks (
id VARCHAR(64) NOT NULL,
premium SMALLINT UNSIGNED NOT NULL DEFAULT '0',
PRIMARY KEY (id),
INDEX premium (premium)
);
```
For now, the table will only contain data for premium network (missing network in this table means non-premium network)
See https://github.com/snapshot-labs/workflow/issues/389#issuecomment-2616078329 for the SQL to import data
Test with this graphql query 
```graphql
query { 
networks { 
id
spacesCount
premium}
}
```
Which should return something like
```json
{
"data": { …
```
=> feat: return premium property for networks

src/graphql/helpers.ts, src/graphql/schema.gql, src/helpers/schema.sql
Toward https://github.com/snapshot-labs/workflow/issues/416
See https://github.com/snapshot-labs/snapshot-sequencer/pull/498 for table creation
This PR will return the `logo` property for the space skin
=> feat: add support for skin logo

src/helpers/spaces.ts
Increases popularity of turbo space when space doesn't have a parent space
=> fix: reduce popularty of turbo subspaces

src/graphql/schema.gql, src/helpers/schema.sql
See: https://github.com/snapshot-labs/workflow/issues/488#issue-2902688159
- Adds a `turbo_expiration_timestamp` in the schema.sql
- Adds a `turbo_expiration_timestamp` in the schema.gql
=> feat: turbo_expiration_timestamp

src/graphql/helpers.ts
- Added logic to ensure quorum only applies to basic voting types
- Defaulted quorum and quorumType for non-basic voting scenarios
Fixes https://github.com/snapshot-labs/workflow/issues/522
- Start the server and use a query like below:
```graphql
{
proposals(where:{id:"0xd07e5c85dae5f59dc444838cbfba8ecf6bd5cabdc3e3787bfa7559877bfd2b1d"}) {
id
quorum
quorumType
}
}
```
| Proposal ID                                                                                                        | Proposal Type | Quorum Type     |  With new changes |
|--------------------------------------------------------------------------------------------------------------------|-------------|------------------|--------|
| [0xd07e5c85dae5f59dc444838cbfba8ecf6bd5cabdc3e3787bfa7559877bfd2b1d](https://snapshot.box/#/ …
=> fix: proposal quorum should only work with basic voting

src/graphql/operations/proposals.ts, src/graphql/schema.gql
- allow sorting with `votes` in proposals query
- Introduced additional vote filters: `votes`, `votes_gt`, `votes_gte`, `votes_lt`, `votes_lte`
Use queries like:
```Graphql
{
proposals(orderBy: "votes", orderDirection: desc) {
votes
}
}
```
```GraphQL
{
proposals(orderBy: "votes", orderDirection: desc, where:{votes_gt: 100000}) {
id
votes
}
}
```
=> fix: allow sorting with `votes` in proposals query

src/graphql/helpers.ts
Toward https://github.com/snapshot-labs/workflow/issues/420
Use the new `turbo_expiration` field to deduce a space's turbo status.
In case expiration is empty, will fallback to the previous `turbo` field for backward compatibility.
This is a soft migration, once all the existing turbo spaces have a proper expiration date, we will remove the `turbo` field for good
=> feat: use turbo expiration field to deduce turbo status

src/helpers/spaces.ts
Fixes https://github.com/snapshot-labs/snapshot-hub/issues/1005
This PR fix an issue where a space is not considered as turbo, even if the turbo expiration date is in the future
=> fix: infer turbo status from turbo expiration date

src/graphql/operations/plugins.ts, src/graphql/operations/skins.ts, src/graphql/operations/validations.ts, src/helpers/spaces.ts, src/helpers/strategies.ts
Closes https://github.com/snapshot-labs/workflow/issues/544
Remove usage and delete the global `spaces` object from helpers/spaces.ts
This object is huge, and contains all the spaces settings, and is also 90% redundant with the `spacesMetadata` object.
Run 
```graphql
query { 
strategies {
id
spacesCount
}
}
```
It should return the same results as before this PR. Same with `skins`, `plugins` and `validations` entity.
- before PR app memory usage: 265mb
- after PR app memory usage: 128mb
=> fix: remove usage of global `spaces` object

src/helpers/spaces.ts
- updated isTurbo function to accept boolean for turbo status
- use following query to see correct space order sorted by popularity
```GraphQL
{
ranking(first:10){
items {
id
rank
}
}
}
```
=> fix: improve turbo status handling for spaces

src/graphql/helpers.ts
When fetching spaces using the `controller` filter, it was previously only returning spaces from the ens.
This PR adds support for also returning spaces from shibarium
Set network to `testnet` in .env, and connect to the testnet database
```graphql
query Spaces {
spaces(first: 20, skip: 0, where: {controller: "0x91FD2c8d24767db4Ece7069AA27832ffaf8590f3"}) {
id
name
}
}
```
This should return a mix of .eth and .shib spaces
=> fix: return shibarium spaces when fetching spaces by controller

src/graphql/operations/messages.ts
Fixes https://github.com/snapshot-labs/workflow/issues/585
The messages fetching query is using the `timestamp` index, instead of the `space` index, which is more appropriate when filtering by spaces.
This PR forces a query with spaces filtering to use the space index.
The same graphql mentioned in the issue should resolve in less than 5s
It's not using multiple index in the `USE INDEX()` (even it supported), from my tests, only using 2 index is as slow as before this PR
=> perf: optimize messages query

src/graphql/operations/proposals.ts, src/graphql/operations/votes.ts
Allow passing starknet address when searching:
- proposals by author
- votes by voter
```graphql
query r {
proposals(where: { author: "0x02a0a8f3b6097e7a6bd7649deb30715323072a159c0e6b71b689bd245c146cc0"}
) {
id
}
}
```
=> feat: allow starknet addresses in proposals and votes

src/helpers/mysql.ts
=> chore: enable SSL with rejectUnauthorized
