- server/helpers/adapters/mysql.ts
- server/index.ts
Fixes https://github.com/balancer-labs/snapshot/issues/214
- When message is `delete-proposal` change the proposal type to `archive-proposal`.
- We might need to increase the `type VARCHAR(12) NOT NULL,` to fit it.
-
> feat: Delete proposal

- server/helpers/mysql.ts
Fixes https://github.com/snapshot-labs/snapshot/issues/265
> Emoji in id error fix

- package-lock.json
- package.json
make sure to merge https://github.com/snapshot-labs/snapshot.js/pull/155 this first
> Snapshot.js from github master

- server/helpers/eip1271.ts
Fixes https://github.com/snapshot-labs/snapshot-hub/issues/37.
- Added legacy EIP1271 implementation ABI to support related Smart Contract wallets.
> added support for older eip1271 implementations

- server/helpers/adapters/mysql.ts
- server/index.ts
- server/writer/delete-proposal.ts
- server/writer/index.ts
- server/writer/proposal.ts
- server/writer/settings.ts
- server/writer/vote.ts
On this PR I just move the logic for each message type (proposal, vote, settings, delete-proposal) in separated files.
> Separate message logic by type

- index.ts
- server/graphql/example.ts
> Add sample query in GraphiQL

- index.ts
- server/helpers/mysql.ts
- server/helpers/spaces.ts
- server/index.ts
- Adding a timeout of 2sec before loading the space, the query been failing before i assume it's just because the function was executed before mysql connection was confirmed.
- Also remove the reloading of all the spaces with ENS (using loadSpaces)
> Fix space loading

- server/helpers/utils.ts
- server/writer/delete-proposal.ts
check if admin/owner for https://github.com/snapshot-labs/snapshot/pull/345
> Allow admins to archive any proposal from their space

- package-lock.json
- package.json
- server/graphql/examples.ts
- server/graphql/helpers.ts
- server/graphql/index.ts
- server/graphql/schema.gql
- server/helpers/adapters/mysql.ts
- server/helpers/spaces.ts
> Use proposals table for GraphQL

- server/graphql/operations/space.ts
- server/graphql/operations/votes.ts
- server/graphql/schema.gql
When we query for votes on the GraphQL API it return the proposal id. 
```gql
{
votes {
voter
proposal
...
}
}
```
On this PR we're changing this so it return the proposal object like this:
```gql
{
votes {
voter
proposal {
id
title
...
}
}
}
```
> Add proposal obj within votes operation

- server/helpers/adapters/mysql.ts
- server/index.ts
- server/writer/delete-proposal.ts
- server/writer/vote.ts
> Use proposal strategies on hub to verify voting power for a vote

- INSTALL.md
File path changed
Fixes # .
- 
- 
-
> update scheme.sql's link

- src/helpers/adapters/mysql.ts
- src/helpers/database/schema.sql
> Remove message payload

- src/routes/api.ts
> Add network param for all spaces in explore endpoint

- src/helpers/adapters/mysql.ts
- src/helpers/spaces.ts
- src/routes/api.ts
> Proposals count and 1d count to explore endpoint

- src/index.ts
fixes #85
> As early as possible in your application, require and configure dotenv.
https://www.npmjs.com/package/dotenv
> read env file before importing other stuff

- src/graphql/helpers.ts
- src/graphql/schema.gql
> Voting delay, period, type and quorum types

- src/helpers/database/schema.sql
> increase max size for message type field in db

- src/writer/vote.ts
> Fix quadratic voting for negative values

- src/graphql/helpers.ts
- src/graphql/schema.gql
For https://github.com/snapshot-labs/snapshot/issues/996
> Add blind property

- src/graphql/helpers.ts
- src/graphql/schema.gql
Fixes https://github.com/snapshot-labs/snapshot/issues/1120
Snapshot PR: https://github.com/snapshot-labs/snapshot/pull/1124
> Basic voting "hide abstain" option

- src/helpers/adapters/mysql.ts
- src/writer/proposal.ts
> Proposal limit

- src/helpers/adapters/mysql.ts
Fixes https://github.com/snapshot-labs/snapshot/issues/1130
> Fix proposal limit SQL

- src/graphql/examples.ts
- src/graphql/helpers.ts
- src/graphql/schema.gql
This reverts commit 124844b66c929cdbbcf5ba788d4fa673a807915f.
Fixes # .
- 
- 
-
> Revert "feat(): add network property to strategy (#262)"

- src/graphql/examples.ts
- src/graphql/helpers.ts
- src/graphql/operations/votes.ts
- src/graphql/schema.gql
Adds network to the space strategy.
> Network strategy

- src/writer/proposal.ts
Fixes https://github.com/snapshot-labs/snapshot/issues/1895
> Invalid voting type

- src/writer/profile.ts
> removed unused params

- src/ingestor/personalSign/utils.ts
Related https://github.com/snapshot-labs/snapshot/issues/2492
> Use brovider

- src/graphql/operations/index.ts
- src/graphql/operations/messages.ts
- src/graphql/schema.gql
- src/ingestor/writer/vote.ts
> Add messages operation

- src/api.ts
- src/ingestor/writer/proposal.ts
- src/ingestor/writer/vote.ts
- src/scores.ts
This PR also remove the loop to update proposal scores
> Update proposal scores on new vote

- src/ingestor/typedData/index.ts
Change typed data ingestor to support vote and proposal action with alias
> Allow alias based msgs for vote and proposal actions

- src/ingestor/typedData/index.ts
Related to https://github.com/snapshot-labs/snapshot-relayer/issues/46
> Increase typed data delay like personalSign

- src/graphql/helpers.ts
- src/ingestor/typedData/index.ts
> metadata in vote

- src/graphql/schema.gql
Fixes https://github.com/snapshot-labs/snapshot-hub/issues/536
> Add guidelines and template to space query

- src/graphql/examples.ts
- src/graphql/helpers.ts
- src/graphql/schema.gql
This PR add space moderators in the GraphQL API.
> feat: expose space moderators on the API

- src/graphql/helpers.ts
- src/graphql/operations/votes.ts
- src/graphql/operations/vp.ts
- src/helpers/spaces.ts
Important: Merge this only after merging https://github.com/snapshot-labs/snapshot-sequencer/pull/34
> Ignore deleted spaces

- .github/workflows/build-test.yaml
- jest.config.ts
- package.json
- test/.env.test
- test/e2e/graphql.test.ts
- test/e2e/space.test.ts
- yarn.lock
- Setup test environment
- Add some basic todo tests
> chore: setup test env and add some basic test to implement

- src/helpers/strategies.ts
Fix #643 
Fix SNAPSHOT-HUB-R
JSON-RPC error response where parsed as a valid response
> fix: do not process JSON-RPC error response

- src/helpers/strategies.ts
> fix: typo fix

- src/helpers/metrics.ts
- src/helpers/requestDeduplicator.ts
We have no metrics about how many saving with got with the requests deduplicator
Instrument the request deduplicator
- Add counters to track number of items in the deduplicator queue
- N/A
> chore: instrument requests deduplicator

- src/helpers/metrics.ts
We have no metrics about how many requests are rate-limited
Instrument the rateLimit middleware, and start counting request that are rate limited 
- Add counters to track number of requests which are not rate limited
- Add counters to track number of requests which are rate limited
- `yarn dev`
- Visit some url
- Visit `/metrics`
- There should be a counter in the form: 
```
http_requests_by_rate_limit_count{rate_limited="0"} 2
```
> chore: instrument rate limited requests

- src/helpers/metrics.ts
This PR add metrics to track the number of open connections to the expressjs server
> chore: instrument open connections count

- src/graphql/operations/messages.ts
- src/graphql/schema.gql
- change graphql schema
- it provides functionality for search address in messages
> feat(graphql): add `address` to where query for messages

- src/graphql/operations/aliases.ts
- src/graphql/operations/follows.ts
- src/graphql/operations/messages.ts
- src/graphql/operations/proposal.ts
- src/graphql/operations/proposals.ts
- src/graphql/operations/statement.ts
- src/graphql/operations/statements.ts
- src/graphql/operations/subscriptions.ts
- src/graphql/operations/user.ts
- src/graphql/operations/users.ts
- src/graphql/operations/vote.ts
- src/graphql/operations/votes.ts
- src/graphql/operations/vp.ts
- https://discord.com/channels/955773041898573854/1030772407226601522/1158324189103661096
- 
GraphQl's response without `new Error`:
```
"message": "Unexpected error value: \"address is required\"",
```
with `new Error`:
```
"message": "address is required",
```
> fix: Return error inside Promise.reject

- src/graphql/helpers.ts
- src/graphql/operations/proposals.ts
- src/helpers/moderation.ts
- src/helpers/spaces.ts
Remove backwards compatibility for fetching flagged proposals and flagged/verified spaces from Laser DB
> refactor(flag): remove old approach for flagged proposals

- src/api.ts
Fixes #478 and #413 
Return a 404 error when the space is not found
> fix: return error when space does not exist

- package.json
- src/graphql/operations/vp.ts
- yarn.lock
This reverts commit 3a3a3fb7e50531148157c38d0dc075f39be52d12.
Fixes # .
- 
- 
-
> Revert "fix: upgrade snapshot.js to 0.8.0 beta.0 (#702)"

- src/helpers/metrics.ts
- Add metric to track the number of flagged spaces
- Remove the unverified spaces metrics (already can be computed from total_spaces - verified_spaces)
> chore: instrument flagged spaces count

- src/helpers/metrics.ts
This PR add a metric to track the total count of spaces.
> chore: add metrics to track total count of spaces

- src/helpers/spaces.ts
> feat: Increase populairity if space is turbo

- src/graphql/helpers.ts
- src/helpers/moderation.ts
Fix error when `flaggedLinks` is not valid (not an array of string, or empty)
Fix #778 
Fix [SNAPSHOT-HUB-1N](https://snapshot-labs.sentry.io/issues/4773352263/?referrer=github_integration)
- Check that array is valid before manipulation
- Add check to ensure flaggedLinks is always an array
- Check that flaggedLinks is not empty before use
> fix: fix error when `flaggedLinks` is not valid

- src/helpers/metrics.ts
Instrument the number of proposals with `pending` scores state
> chore: instrument pending scores proposals

- src/eip4824.ts
- src/index.ts
This PR a new REST API to support EIP-4824 https://eips.ethereum.org/EIPS/eip-4824
To test go on this URLs:
http://localhost:3000/api/eip4824/stgdao.eth
http://localhost:3000/api/eip4824/stgdao.eth/members
http://localhost:3000/api/eip4824/stgdao.eth/proposals
http://localhost:3000/api/eip4824/stgdao.eth/activities
http://localhost:3000/api/eip4824/stgdao.eth/contracts
http://localhost:3000/api/eip4824/wrong-space.eth
http://localhost:3000/api/eip4824/wrong-space.eth/members
> feat: add support for EIP-4824

- src/graphql/operations/roles.ts
- src/graphql/operations/space.ts
- src/graphql/operations/vote.ts
- src/graphql/schema.gql
Fixes #835 
Fixes [SNAPSHOT-HUB-2E](https://snapshot-labs.sentry.io/issues/5049433005/?referrer=github_integration)
- Enforce presence of required argument in the gql schema, so that error is thrown when missing, else it will continue and fail with an invalid SQL query error.
> fix: throw error on missing required query argument

- src/graphql/schema.gql
Expose fields added by https://github.com/snapshot-labs/snapshot.js/pull/1011
> feat: return more user profile details

- src/helpers/schema.sql
Same as https://github.com/snapshot-labs/snapshot-sequencer/pull/384
> fix: Increase statements id length

- src/graphql/schema.gql
Related to https://github.com/snapshot-labs/sx-monorepo/pull/419
Return the new `lens` and `farcaster` properties from User
> feat: return lens and farcaster from user

- src/helpers/schema.sql
Change length of all address fields 
```SQL
ALTER TABLE proposals MODIFY COLUMN author VARCHAR(100) NOT NULL;
ALTER TABLE votes MODIFY COLUMN voter VARCHAR(100) NOT NULL;
ALTER TABLE follows MODIFY COLUMN follower VARCHAR(100) NOT NULL;
ALTER TABLE aliases MODIFY COLUMN address VARCHAR(100) NOT NULL, MODIFY COLUMN alias VARCHAR(100) NOT NULL;
ALTER TABLE subscriptions MODIFY COLUMN address VARCHAR(100) NOT NULL;
ALTER TABLE users MODIFY COLUMN id VARCHAR(100) NOT NULL;
ALTER TABLE leaderboard MODIFY COLUMN user VARCHAR(100) NOT NULL;
```
> fix: Change length of address fields and add leaderboard to schema

- src/graphql/operations/aliases.ts
- src/graphql/operations/follows.ts
- src/graphql/operations/proposals.ts
- src/graphql/operations/statements.ts
- src/graphql/operations/subscriptions.ts
- src/graphql/operations/user.ts
- src/graphql/operations/users.ts
- After changing collate of tables we have to support lowercased address like before, else many integrator's existing code may break
> fix: handle lowercased addresses in inputs

- src/graphql/operations/user.ts
> hotfix: return only user if exists

- src/graphql/operations/statements.ts
- src/graphql/schema.gql
This PR add  `network` to Statements where field
> fix: add network filter to statements query

- src/eip4824.ts
Fixes # .
- Add Content URI Field, which includes Author, IPFS hash, Body, Link of the proposal
- Add Discussion URI Field, which includes the forum discussion link
Reference Issues:
- https://github.com/metagov/daostar/issues/203
- https://github.com/metagov/daostar/issues/239
> DAOstar Collab: Improve ProposalsURI - Publish more info for proposals

- Dockerfile
> chore: fix typo for Dockerfile

- src/graphql/helpers.ts
Reverts snapshot-labs/snapshot-hub#992
> Revert "fix: proposal quorum should only work with basic voting"

- src/graphql/operations/options.ts
- src/helpers/spaces.ts
- src/helpers/strategies.ts
Toward https://github.com/snapshot-labs/workflow/issues/544
Migrate away from recursive calls
> refactor: avoid recursive calls

- src/helpers/mysql.ts
- src/index.ts
Context https://discord.com/channels/955773041898573854/1397533764648833154/1397544545167867974
Summary:
This will gracefully shutdown server and close DB connection on process end
Changes:
Same as https://github.com/snapshot-labs/keycard/blob/master/src/index.ts#L32-L50
> chore: graceful shutdown

- src/helpers/mysql.ts
- test/.env.test
- change ssl rejectUnauthorized to check if host is localhost 🔒
- update database URLs in test environment to use localhost instead of 127.0.0.1 🌐
> fix: tests not working with DB connection
